apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shift-scheduler-pvc
  namespace: shift-scheduler-ns
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
